CREATE VIEW CO_AUTHORS
AS
SELECT A1.PAPER_ID, A1.AUTHOR_NAME AS A1_NAME, A2.AUTHOR_NAME AS A2_NAME
FROM AUTHORS A1
JOIN AUTHORS A2
ON A1.AUTHOR_NAME > A2.AUTHOR_NAME AND A1.PAPER_ID = A2.PAPER_ID;
CREATE VIEW NUMBER_OF_PAPERS
AS
SELECT A1_NAME, A2_NAME, COUNT(*) AS NO_OF_PAPERS
FROM CO_AUTHORS
GROUP BY A1_NAME, A2_NAME;
SELECT * FROM NUMBER_OF_PAPERS
WHERE NO_OF_PAPERS > 1;