CREATE VIEW PAPER_DETAILS
AS 
SELECT PAPER.PAPER_ID, PAPER.TITLE, PAPER.YEAR, VENUES.VENUE_NAME, AUTHORS.AUTHOR_NAME, PAPER.ABSTRACT
FROM PAPER
LEFT JOIN VENUES
ON PAPER.PAPER_ID = VENUES.PAPER_ID
LEFT JOIN AUTHORS
ON PAPER.PAPER_ID = AUTHORS.PAPER_ID;
CREATE VIEW PAPER_AND_REF
AS
SELECT PAPER.PAPER_ID AS PAPER_ID, REF.REFERENCE_ID AS REFERENCE_ID
FROM PAPER
LEFT JOIN REF
ON PAPER.PAPER_ID = REF.PAPER_ID;
SELECT PAPER_AND_REF.PAPER_ID, PAPER_AND_REF.REFERENCE_ID, PAPER_DETAILS.TITLE, PAPER_DETAILS.YEAR, PAPER_DETAILS.VENUE_NAME, PAPER_DETAILS.AUTHOR_NAME, PAPER_DETAILS.ABSTRACT
FROM PAPER_AND_REF
LEFT JOIN PAPER_DETAILS
ON PAPER_AND_REF.REFERENCE_ID = PAPER_DETAILS.PAPER_ID
ORDER BY PAPER_ID;