CREATE VIEW PAPER_DETAILS
AS 
SELECT PAPER.PAPER_ID, PAPER.TITLE, PAPER.YEAR, VENUES.VENUE_NAME, AUTHORS.AUTHOR_NAME, PAPER.ABSTRACT
FROM PAPER
LEFT JOIN VENUES
ON PAPER.PAPER_ID = VENUES.PAPER_ID
LEFT JOIN AUTHORS
ON PAPER.PAPER_ID = AUTHORS.PAPER_ID;
CREATE VIEW PAPERS_THAT_CITE
AS
SELECT PAPER.PAPER_ID AS PAPER_ID, REF.PAPER_ID AS PAPER_THAT_CITES
FROM PAPER
LEFT JOIN REF
ON PAPER.PAPER_ID = REF.REFERENCE_ID;
SELECT PAPERS_THAT_CITE.PAPER_ID, PAPERS_THAT_CITE.PAPER_THAT_CITES, PAPER_DETAILS.TITLE, PAPER_DETAILS.YEAR, PAPER_DETAILS.VENUE_NAME, PAPER_DETAILS.AUTHOR_NAME, PAPER_DETAILS.ABSTRACT
FROM PAPERS_THAT_CITE
LEFT JOIN PAPER_DETAILS
ON PAPERS_THAT_CITE.PAPER_THAT_CITES = PAPER_DETAILS.PAPER_ID
ORDER BY PAPER_ID;